#include "answer.h"

/*
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int answer(void)
{
    unsigned long fibonacci = 0;
    unsigned long prev1 = 55;
    unsigned long prev2 = 89;
    unsigned long sum = 2 + 8 + 34;
    
    while (fibonacci <= 4000000)
    {
       fibonacci = prev1 + prev2;
       prev1 = prev2;
       prev2 = fibonacci;
       
       if ((fibonacci % 2) == 0)
         sum += fibonacci;
    }
    
    printf("Sum is %lu\n", sum);

    return 6 * 7;
}

